### ISSUE TITLE
Upload an Image

### ISSUE THREAD

**Issue by piep14** [waynestate/nova-ckeditor4-field#19] opened 2019-05-03 14:36 UTC
How add this tabs ? Thank you

![image](https://user-images.githubusercontent.com/3505174/57144576-a07a5c00-6dc1-11e9-9696-37ddd4ba12db.png)

**Comment by chrispelzer** [comment] 2019-06-04 17:46
Closing out due to duplicate of #4 

There's currently no ability to upload an image through CKEditor itself with the current nova field.

**Closed by chrispelzer** 2019-06-04 17:46 UTC
