### ISSUE TITLE
Integration with Filemanager Package

### ISSUE THREAD

**Issue by KnowledgeWanderer** [waynestate/nova-ckeditor4-field#24] opened 2019-09-17 20:08 UTC
So I am using this package https://github.com/InfinetyES/Nova-Filemanager for my Laravel Nova App and it would be cool if I could replace the button from the toolbar ( the image upload one ) with an instance of the filemanager and then automatically translate it into the field.

Is there any way of doing this? Thanks

**Comment by robertvrabel** [comment] 2019-09-19 11:16
I believe you can through customizing the config https://github.com/waynestate/nova-ckeditor4-field#overriding-config-values . This issue might have helpful information as well: https://github.com/waynestate/nova-ckeditor4-field/issues/4

I don't have any specific code to offer since I haven't done it myself, but @chrispelzer may be able to provide some direction as well.

**Comment by KnowledgeWanderer** [comment] 2019-09-30 13:14
Looked into it, but it's a bit overwhelming as of now and I could use some guidance as I can't find anything related to uploading and the config. Any ideas @chrispelzer ?

**Comment by chrispelzer** [comment] 2019-09-30 14:19
Closing out due to duplicate of #4

There's currently no ability to upload an image through CKEditor itself with the current nova field.

If you are able to contribute code for it that would be appreciated, 
I would probably take a look at how https://unisharp.github.io/laravel-filemanager/integration handles the file uploads and see if it could be tied in with the Nova-Filemanager package.

**Closed by chrispelzer** 2019-09-30 14:19 UTC
